[project]
name = "attempt-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pydantic>=2.12.3",
    "pandas>=2.0.0",
    "openpyxl>=3.0.0",
    "pyyaml>=6.0",
]
